"""add user email_notifications preference

Revision ID: 214c3b978aa7
Revises: 37ac1bc9540d
Create Date: 2026-10-06 16:55:28.516458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '214c3b978aa7'
down_revision: Union[str, Sequence[str], None] = '37ac1bc9540d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; the column is NOT NULL
    op.add_column(
        'users',
        sa.Column('email_notifications', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications')
    # ### end Alembic commands ###
